### ISSUE TITLE
Hey Shaun do the scripts in this repo work??

### ISSUE THREAD

**Issue by davidcorbin** [ShaunJorstad/gcc-nix#1]

**Comment by ShaunJorstad** [comment]
Yes. I haven't tested them since I copied them from the development repo but they should work. I'll have a more definitive answer in a few days. I also have a script to install the printer that is currently behind the helpdesk. I'm not going to publish that script, nor do I know if the printer will remain in its current location during the school year. If it does I can send it to you. The same scripts have been made available on the \\depot server but I figure a github repo will be easier to share.

I intend to write a script to configure the vpn's on linux environments but haven't gotten around to it

**Comment by davidcorbin** [comment]
That's awesome man! Great work!

I'll definitely use them and share them. 

Are you working for the Helpdesk this summer?

**Comment by ShaunJorstad** [comment]
Thanks David! Feel free to improve them, I don't use MacOS so if something breaks I won't know. 

Yes I am.

**Comment by davidcorbin** [comment]
Absolutely! I'm gonna try them on Linux and Mac to see if they work! 👍🏻
